.\"
.\" DB-EXPORT.1 --Manual page for "db-export"
.\"
.TH db-export 1 "" "" "Admin Kit"
.SH NAME 
db-export \- export some mysql databases to SQL files.
.SH SYNOPSIS
.SY db-export
.OP -h host
.OP -u user
.OP -p password
.OP -r root
.OP -s suffix
.OP -m message
.OP -z
.OP -f
.OP -q
.OP -v
.I databases ...
.YS
.SY db-export
.OP -i ignore-patterns
.OP -h host
.OP -u user
.OP -p password
.OP -r root
.OP -s suffix
.OP -m message
.OP -z
.OP -f
.OP -q
.OP -v
.YS
.SH DESCRIPTION
The 
.B db-export
command connects to a mysql server and exports the specified schemas
to SQL files named after the schema.  This is just a convenience wrapper
around 
.B mysqldump
and
.BR gzip .

The schemas are dumped into files named 
.IR root / schema "" suffix ; 
the default root is ".", and the default suffix is ".sql", so by
default files are output to 
.RI ./ schema .sql.
Both the root and the suffix can be specified by command line options
(see below).

If the 
.B \-\-compress
option is specified, the resulting files will be compressed using
.BR gzip , 
and will have an additional ".gz" extension (i.e. 
.RI ./ schema .sql.gz)

.B db-export
will also write SQL comments into the dump file recording the start
and end time of the dump operation.  An additional comment can be
included via the 
.B \-\-message 
option.
.SH OPTIONS
.TP
.BI \-h\  host
.TQ
.BI \-\-host\fR= hostname
Connect to the MySQL database server located on server 
.IR hostname .
.TP
.BI \-u\  user
.TQ
.BI \-\-user\fR= user
Connect to the MySQL database server as the user 
.IR user .
.TP
.BI \-u\  password
.TQ
.BI \-\-password\fR= password
Specifies the MySQL connection password.
.TP
.BI \-i\  pattern,pattern,...
.TQ
.BI \-\-ignore\fR= pattern,pattern,...
Ignore the database schemas that match the comma-separated regex
patterns.
This option is only used if no schemas are specified after the options
on the command line.
The default value is "mysql,*_schema,.*test.*", which naturally
excludes all the schemas that MySQL creates for its internal use.
.TP 
.BI \-r\  directory
.TQ
.BI \-\-root\fR=  directory
Specifies the root directory of SQL dump file (default ".").
.TP 
.BI \-s\  suffix
.TQ
.BI \-\-suffix\fR= suffix
Specifies the suffix (after the schema name) for the SQL dump file 
(default ".sql").
.TP 
.BI \-m\  message-text
.TQ
.BI \-\-message\fR= message-text
Add a SQL comment text message at the start of the dump.
.TP 
.B \-z
.TQ
.B \-\-compress
Compress the resulting SQL dump file using 
.BR gzip (1).
.TP 
.B \-f
.TQ
.B \-\-force
Pass the 
.B \-\-force
option to
.BR gzip (1).
Normally 
.B gzip
will avoid overwriting an existing file, this options forces it do so.
.SH "EXIT STATUS"
.B db-export
returns 2 if there was an error in the command line
arguments, 1 if connection to the database server fails.
.SH SEE ALSO
.BR gzip (1),
.BR mysqldump (1)
